### ISSUE TITLE
Extend scope support in double quotes.

### ISSUE THREAD

**Issue by ctf0** [mrmartineau/HTML5#17]
is it possiable to support somthing like this ?

![ee59f7c6-a897-11e4-883b-db88a9a21806](https://cloud.githubusercontent.com/assets/7388088/6080234/bd8f8f86-ae17-11e4-815d-768bba6a53df.jpg)

this will make working with angular.js & laravel blade a breeze.

for reference
https://github.com/suryatech/codeschool-shaping-up-with-angular/issues/1
https://github.com/angular-ui/AngularJS-sublime-package/issues/76

**Comment by mrmartineau** [comment]
Hey @ctf0, I'm not actually sure what you want to achieve..

**Comment by ctf0** [comment]
add some regex to detect things like '(number)', `panel.xxx`, `{...}`so we can color them differently ,as currently anything inside the double quotes are treated the same and will get the same coloring.

this is more of a cosmetic/syntax coloring request to help with working on angular.js projects,etc..

**Comment by ghost** [comment]
HTML5 package has HUGE ST3 problem - (GitHub no comment, so post here, please followup / fix)
Problem is HTML5 package causes tag snippets to duplicate first carrot. Carrots nukes everywhere!
Problem consistent across millions of machines. Please fix, mrmartineau.
![html5](https://cloud.githubusercontent.com/assets/11430826/10525304/cdb200c4-7338-11e5-873c-c33a9d152af5.PNG)

.

**Comment by swirly** [comment]
Same problem as anyotherway

When I start typing <bo for body, I have multiples choices in the contextual menu
body     <body>
body    Tag
body    Tag
the first choice (by default) will result in a double opening inferior sign
<<body></body>
second and third choice (why 3 choices ????) will result in correct result

In fact, one of the "Tag" choice is coming from HTML package.
But, if I disable HTML package, I loose everything

So far for investigation

**Comment by LOQUILLO** [comment]
Hi @swirly, @anyotherway, your have the problem "tag snnipets duplicated" yet?

**Comment by ctf0** [comment]
https://github.com/mrmartineau/HTML5/issues/23
