### ISSUE TITLE
The plugin doesn't work

### ISSUE THREAD

**Issue by Deorro** [mrmartineau/HTML5#18]
Hi.

He had previously installed the plugin in sublime text 2 and worked very well when I appeared choose HTML5 syntax.

But today I reinstalled on another PC and when I want to select the syntax of HTML document just me, not HTML5 as before.

I leave you screenshots, what I can do?

Now:

http://prntscr.com/6d71qu

Before:

http://i.imgur.com/UNMQoMQ.png

**Comment by treedbox** [comment]
It's normal here, try close and open your Sublime.
Any html or html5 will work

**Comment by Deorro** [comment]
Yes, I restart sublime and the problem continues.

**Comment by Tiendq** [comment]
Me too, there are 2 HTML items in the menu. Reinstall didn't help.

**Comment by alphanull** [comment]
I have the same issue - 2 "HTML" Items which are both active. Should be called "HTML5" and ideally detect syntax using the doctype.

**Comment by ctf0** [comment]
after the last update the item will be **HTML** in the syntax list, u should disable the default html package that come with ST.

**Comment by alphanull** [comment]
Wouldn't it make more sense to simply call it HTML5? After all sometimes there is still some older stuff to work on which isn't HTML5 (yet). Also feels strange that for an addon to work one has to delete the builtin stuff.

**Comment by ctf0** [comment]
@alphanull simply the default package is outdated and this one adds lots of new tags ,so disabling the original makes sens, like other packages "js,css,etc.."

**Comment by alphanull** [comment]
And how exactly do I install this then?

**Comment by ctf0** [comment]
disable the default and install this

**Comment by alphanull** [comment]
OK, I disabled the builtin HTML packe (via package control) and then (re)installed the HTML5 Package. But now that results in:

Error loading syntax file "Packages/HTML5/HTML.tmLanguage": Unable to find HTML.sublime-syntax

**Comment by treedbox** [comment]
mrmartineau say: 
"I actually have this package disabled because Emmet is so much better. You guys should check it out." https://github.com/mrmartineau/HTML5/issues/14#issuecomment-87389781
http://emmet.io/

**Comment by alphanull** [comment]
I do not want emmet ... so please give me EXACT instructions how to get this to work. About to give up bc its starts to be really annoying :(

**Comment by treedbox** [comment]
after disable, restart sublime
done that?

**Comment by alphanull** [comment]
sure

**Comment by treedbox** [comment]
Seems that u have deleted "html5" folder because the sublime don't find the HTML.tmLanguage file.
just download and unzip in Package/HTML5 folder
https://github.com/mrmartineau/HTML5/archive/master.zip
restart and it should work.

**Comment by alphanull** [comment]
That folder was never there. OK so I installed it, but now I get the next error message:

Error loading syntax file "Packages/SublimeLinter/fixed-syntaxes/HTML/HTML.tmLanguage": Unable to open Packages/SublimeLinter/fixed-syntaxes/HTML/HTML.tmLanguage

So this is incompatible with sublime linter as well?

**Comment by alphanull** [comment]
Sorry this is ridiculous. PLEASE can anyone tell me how to modify this so that the Syntax is shown as HTML5, OR how to install this so that it does NOT interfere with ANYTHING else. Or else I have to ditch this and live with the error messages. But as it stands it is just unusable at least for me, never had so much trouble with any other plugin. Sorry!

**Comment by ctf0** [comment]
here is what i did, 
1- remove the HTML.sublime-package from the ST installation (depends on whether u use OSX or WIN)
2- install this package like any other without disabling anything.

**Comment by Tiendq** [comment]
I tried to remove original HTML package, and installed HTML5. There is no error until now but it seems that HTML5 package doesn't work, HTML5 new tags aren't highlighted. And I got 2 HTML items on the menu, but none or both selected.

Leaving the origin HTML doesn't harm anyone, so making a name conflict is really annoying. This ticket is completely wasting time of users. I hope that the author renamed it back to HTML5, at least, please don't introduce any compatibility issue.

Thanks,

**Comment by AuthorProxy** [comment]
A lot of problems after upgrade, agree with other, installation is difficult now, a lot of errors and misunderstanding after renaming to "HTML"

**Comment by alphanull** [comment]
Sorry, I won't physically remove parts from the ST package itself, this is the same as asking for deleting parts of Photoshop when just installing a plugin. Of course this has to be done then for each upgrade of ST itself, and it just feels wrong. At this point it should be clear that this is not a very good way and it seems I am not the only one having problems. So PLEASE, rename it just to HTML5 again (or provide at least some install options), and I am sure you have less conflicts than before. Maybe the best solution would be to approach the ST team, and try to get this rolled in into the native package, this is severly outdated anyways.

**Comment by alphanull** [comment]
Ah and I also have a "HTML prettify" plugin as well. This could be the next one having problems, so I won't try to get all of this working after already wasting several hours on this for nothing. Am very sorry to say this since I am sure this is a useful and needed addition, but please do not try to make it install this way. Thanks!

**Comment by mrmartineau** [comment]
Is the issue with the `.tmLanguage` name being HTML not HTML5? If so, I'll rename it back. This happened in a recent pull request.

**Comment by mrmartineau** [comment]
Please see #21 regarding this issue

**Comment by maher17** [comment]
try install it with package control it will work 100% , and you should never install package manually just install it with package control
