### ISSUE TITLE
HTML5 messes with HTML default plugin

### ISSUE THREAD

**Issue by miguelbaldi** [mrmartineau/HTML5#19]
When I've installed this plugin on Sublime Text 2, the command "HTML:  encode special characters" was gone.
To fix I've need to remove the "HTML5" package, clear "Packages/HTML" folder and extract the contents from Pristine Packages/HTML.sublime-package.

**Comment by ctf0** [comment]
check #18

**Comment by treedbox** [comment]
mrmartineau say: 
"I actually have this package disabled because Emmet is so much better. You guys should check it out." https://github.com/mrmartineau/HTML5/issues/14#issuecomment-87389781
http://emmet.io/

**Comment by mrmartineau** [comment]
Please see #21 regarding this issue
