### ISSUE TITLE
Consider removing the tmLanguage syntax definition

### ISSUE THREAD

**Issue by mrmartineau** [mrmartineau/HTML5#21]
There are a number of issues (#18, #19, #20) relating to the syntax definition in the package screwing up their version of Sublime. I think that removing the syntax definition will solve these problems but I wanted to get people's opinion on the matter.. Sublime's default HTML syntax is fine for HTML5 so this package could just be related to HTML5 snipperts, what do you all think?

**Comment by Tiendq** [comment]
I heard that upcoming default HTML package will fully support HTML5 syntax too :)

**Comment by mrmartineau** [comment]
I know, I think it's better if I just remove the syntax def so that there are no more conflicts.. does anyone else have an opinion before I get rid of it?
